# 로컬 환경 설정
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: admin
    password: admin
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
        type:
          enum: org.hibernate.type.EnumType

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.jungsan.backend: DEBUG
    org.hibernate.SQL: WARN
