# 프로덕션 환경 설정
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

logging:
  level:
    root: ${LOG_LEVEL_ROOT}
    com.jungsan.backend: ${LOG_LEVEL_APP}
    org.hibernate.SQL: ${LOG_LEVEL_SQL}
